### ISSUE TITLE
Bead structure

### ISSUE THREAD

**Issue by AlicePsyche** [MacoskoLab/slideseq-tools#2]
Hi slideseq-tools developers,

I am reading the documentation and try to set up the pipeline. May I ask that what do the characters stand for in the bead_structure? (`C`, `X`, `M`) I tried to match it with the bead sequences in the supplemental file but failed, so could you please explain them a little bit more? Thanks a lot for your help.

> bead_structure: Specify bead structure such as 8C18X7C8M1X|*T

Best,
Alice

**Comment by jamestwebber** [comment]
Hello! Sorry for the silence on this end for so long! I joined the lab as a computational scientist this year and I've recently started working on improving this pipeline. I didn't notice that there were open issues until this week.

The bead structure is a description of how the slideseq beads were synthesized, which determines R1 for the data. C is a barcode base, X is a throwaway base (unimportant for analysis), M is a UMI base. So the example `8C18X7C8M1X` has a 15-base barcode for the bead (8C + 7C) and an 8-base UMI (8M).

I'm hoping to merge a revised version of the pipeline soon, hopefully it will be easier to understand.
